[project]
name = "worker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "application",
    "bootstrap",
    "infrastructure",
    "dependency-injector>=4.41",
    "taskiq>=0.11",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/worker"]

[tool.uv.sources]
application = { workspace = true }
bootstrap = { workspace = true }
infrastructure = { workspace = true }
